name: showcase_cars_flutter_node_js
description: car showcase using flutter for front-end and node.js for back-end

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=2.19.4 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  cupertino_icons: ^1.0.2
  provider: ^6.0.5
  auto_route: ^7.7.1
  http: ^0.13.6
  shared_preferences: ^2.2.0
  image_picker: ^1.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  flutter_lints: ^2.0.0
  auto_route_generator: ^7.2.0
  build_runner: ^2.3.3

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
